# Programa Ingenias+ Data Science

Primera Pre-Entrega

Alumna: Ruth Cruz


# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.



1. Crear un arreglo de ceros de longitud 12

In [2]:
import numpy as np
arreglo_ceros = np.zeros(12)

print(arreglo_ceros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5

In [4]:


arreglo = np.zeros(10)
arreglo[4] = 10

print(arreglo)


[ 0.  0.  0.  0. 10.  0.  0.  0.  0.  0.]


3. Crear un arreglo que tenga los números del 10 al 49

In [5]:
arreglo_num= np.arange(10, 50)

print(arreglo_num)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8

In [6]:

arreglo2d = np.arange(9).reshape(3, 3)

print(arreglo2d)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza

In [7]:

arreglo_aleat = np.random.rand(100)

# Calcular la media del arreglo
media = np.mean(arreglo_aleat)

# Calcular la varianza del arreglo
varianza = np.var(arreglo_aleat)

print(f"La Media del arreglo es : {media}")
print(f"La Varianza del arreglo es: {varianza}")


La Media del arreglo es : 0.49012173616309485
La Varianza del arreglo es: 0.07673759630524717


6. Calcular la media de un arreglo usando np.sum

In [9]:

arreglo = np.array([1, 2, 3, 4, 5])

suma_t = np.sum(arreglo)

media = suma_t / len(arreglo)

print(f"La Media del arreglo es: {media}")


La Media del arreglo es: 3.0


7. Calcular la varianza de un arreglo usando np.sum y np.mean

In [10]:

arreglo = np.array([1, 2, 3, 4, 5])

# Paso 1: Hay q Calcular la media del arreglo
media = np.mean(arreglo)

# Paso 2: luego  las diferencias al cuadrado entre cada elemento y la media
diferencias_cuadradas = (arreglo - media) ** 2

# Paso 3: Sumar todas las diferencias al cuadrado
suma_dif_cuadr = np.sum(diferencias_cuadradas)

# Paso 4: Dividir por el número de elementos para obtener la varianza
varianza = suma_dif_cuadr / len(arreglo)

print(f"La Varianza del array es: {varianza}")


Varianza del arreglo: 2.0


Crear un array de números aleatorios usando np.random.randn.

In [12]:

arreglo_aleat = np.random.randn(500)

print(arreglo_aleat)


[ 1.45194729 -0.84826106 -0.35371144 -0.37135455 -0.22697783 -1.26720982
  0.79619564  0.90540205  1.162504   -0.90800949 -0.97187273 -1.83700765
  0.96414282  0.79291865  0.4774155  -0.87936908  0.15155887  0.79258063
 -0.37843757  0.10922383 -0.77339575  1.22555037 -1.24046669  0.60477334
  0.07915389  1.56024694  1.33733121 -0.68405973 -0.87024842  0.26350561
  0.63036625  0.39822901 -1.17487972 -0.63846277 -1.19256845 -0.22346971
  0.50219177 -0.005003    0.07699222  0.6894012  -0.42013949 -0.22725114
  0.23774375 -0.45401705  0.84902541 -0.98298088 -0.15794869 -0.47566727
 -0.75957946  0.43200678  1.39816708  0.89408835  1.25014677  0.38691794
  1.66544425  0.92221075 -0.05600741 -0.97046974  1.22985039 -0.91103206
 -0.98695856 -0.23729611  0.17798031 -0.74350811 -0.15341348  0.7486337
 -0.90755983  0.85406061  1.23293412 -0.2182656  -0.76106568 -0.06016911
  0.85601493 -1.42235252  1.21459494  1.8678284   0.04461112  0.33353088
  0.08087997  0.1254948   0.97744176 -0.00618498  1.